framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command_bus
        buses:
            command_bus:
                middleware:
                    - dispatch_after_current_bus
                    - doctrine_transaction
            query_bus:
                middleware:
                    - dispatch_after_current_bus
                    - doctrine_transaction
            event_bus:
                default_middleware: allow_no_handlers
                middleware:
                    - dispatch_after_current_bus
            data_synchronization_command_bus:
                middleware:
                    - dispatch_after_current_bus
                    - doctrine_transaction

        transports:
            async_commands:
                dsn: 'doctrine://default?queue_name=async_commands&auto_setup=0'
            async_events:
                dsn: 'doctrine://default?queue_name=async_events&auto_setup=0'
            failed:
                dsn: 'doctrine://default?queue_name=failed'
            sync:
                dsn: 'sync://'

        routing:
            'App\SharedKernel\Domain\Bus\Command\Command': sync
            'App\SharedKernel\Domain\Bus\Command\AsyncCommand': async_commands
            'App\SharedKernel\Domain\Bus\Event\Event': sync
            'App\SharedKernel\Domain\Bus\Event\AsyncEvent': async_events
            'App\SharedKernel\Domain\Bus\Query\Query': sync
